#William Nguyen
#1824617
lemon = float(input('Enter amount of lemon juice (in cups):'))
print()
water = float(input('Enter amount of water (in cups):'))
print()
nectar = float(input('Enter amount of agave nectar (in cups):'))
print()
servings = float(input('How many servings does this make?'))
print()
print()
print('Lemonade ingredients - yields', '{:.2f}'.format(servings), 'servings')
print('{:.2f}'.format(lemon), 'cup(s) lemon juice')
print('{:.2f}'.format(water), 'cup(s) water')
print('{:.2f}'.format(nectar), 'cup(s) agave nectar')
print()
serving = float(input('How many servings would you like to make?'))
print()
print()
print('Lemonade ingredients - yields', '{:.2f}'.format(serving), 'servings')
print(('{:.2f}'.format(lemon * (serving / servings))), 'cup(s) lemon juice')
print(('{:.2f}'.format(water * (serving / servings))), 'cup(s) water')
print(('{:.2f}'.format(nectar * (serving / servings))), 'cup(s) agave nectar')
print()
print('Lemonade ingredients - yields', '{:.2f}'.format(serving), 'servings')
print(('{:.2f}'.format(lemon * (serving / servings)/16.00)), 'gallon(s) lemon juice')
print(('{:.2f}'.format(water * (serving / servings)/16.00)), 'gallon(s) water')
print(('{:.2f}'.format(nectar * (serving / servings)/16.00)), 'gallon(s) agave nectar')